### ISSUE TITLE
Standard Dissolve Shaders do not work with Deferred Rendering in Unity 2017.3 

### ISSUE THREAD

**Issue by Blueteak** [dimension5/BeautifulDissolves#1]
![screenshot_8](https://user-images.githubusercontent.com/10412514/34645763-dbe0c122-f323-11e7-8264-95cba14c2df5.png)

Works fine when camera is set to Forward Rendering, but no luck when set to Deferred

**Comment by dimension5** [comment]
Hi, so sorry for the late response (my GitHub notifications were turned off.. woops). Issue has been addressed and submitted for review. The update should be out in the asset store within the week.
