### ISSUE TITLE
DissolveUI not instantiating materials

### ISSUE THREAD

**Issue by cfoulston** [dimension5/BeautifulDissolves#3]
Unlike "Dissolve", the UI version does not instantiate materials. Creating runtime modifications on material assets. Consider either using Material Property Blocks, or Instantiating the materials.

Something like this works:

```
public class DissolveUI : Dissolve {

	protected override Material[] GetMaterials()
	{
		Graphic graphic = GetComponentInChildren<Graphic>();

		return graphic != null && graphic.materialForRendering != null ? new Material[]{ graphic.material = Instantiate(graphic.materialForRendering) } : null;
	}
}
```

**Comment by dimension5** [comment]
Hi, so sorry for the late response (my GitHub notifications were turned off.. woops). Issue has been addressed and submitted for review. The update should be out in the asset store within the week.
